"""empty message

Revision ID: 119ed50ca754
Revises: 
Create Date: 2023-05-05 14:42:12.438651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119ed50ca754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
