version: '2.2'
services:
  flask-app-container:
    image: pythondocker-flask-app-container
    container_name: flask-app-container
    environment:
      FLASK_APP: main.py
    ports:
      - 5000:5000
    command: "python -m flask run --host 0.0.0.0"
    